# name: CD Pipeline

# on:
#   workflow_run:
#     workflows: ["Code Check CI Pipeline"]
#     types: [completed]

# jobs:
#   build:
#     name: push to dockerhub
#     runs-on: ubuntu-latest
#     steps:
#       - name: Login to Docker Hub
#         uses: docker/login-action@v3
#         with:
#           username: ${{ vars.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}
